# Generated by Django 6.0.6 on 2026-07-18 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_city_alter_listing_created_at_and_more'),
        ('view_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhistory',
            name='listing',
            field=models.ForeignKey(help_text='Listing viewed by the user.', on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(help_text='User who viewed the listing.', on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time of the latest recorded view.', verbose_name='viewed at'),
        ),
    ]
