# Generated by Django 6.0.6 on 2026-07-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, verbose_name='query')),
                ('search_filters', models.JSONField(blank=True, default=dict, verbose_name='search filters')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Search history entry',
                'verbose_name_plural': 'Search history entries',
                'ordering': ('-created_at',),
            },
        ),
    ]
