# Generated by Django 6.0.6 on 2026-07-18 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_history', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the search was recorded.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(db_index=True, help_text='Keyword phrase entered by the user.', max_length=255, verbose_name='query'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Additional listing filters used together with the query.', verbose_name='search filters'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(help_text='User who performed the search.', on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
