# Generated by Django 6.0.6 on 2026-07-10 01:21

from django.db import migrations


RENTERS_GROUP = "Renters"
LANDLORDS_GROUP = "Landlords"


def create_user_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.get_or_create(name=RENTERS_GROUP)
    Group.objects.get_or_create(name=LANDLORDS_GROUP)


def delete_user_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.filter(
        name__in=[
            RENTERS_GROUP,
            LANDLORDS_GROUP,
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_groups, delete_user_groups),
    ]
