# Generated by Django 6.0.6 on 2026-07-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deactivated at'),
        ),
    ]
