# Generated by Django 6.0.6 on 2026-07-18 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_deactivated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time when the user account was deactivated.', null=True, verbose_name='deactivated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Unique email address used for login.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text="User's first name.", max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text="User's last name.", max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional phone number in international format.', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter the phone number in international format, for example +491234567890.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='phone number'),
        ),
    ]
