# Generated by Django 6.0.6 on 2026-07-10 01:20

import apps.listings.models.listing_image
import apps.listings.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room')], db_index=True, max_length=20, verbose_name='property type')),
                ('price_per_night', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per night')),
                ('rooms', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='rooms')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='city')),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='district')),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Postal code must contain exactly 5 digits.', regex='^\\d{5}$')], verbose_name='postal code')),
                ('street', models.CharField(max_length=150, verbose_name='street')),
                ('house_number', models.CharField(max_length=20, verbose_name='house number')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.listings.models.listing_image.listing_image_upload_path, validators=[apps.listings.validators.validate_listing_image_size], verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
            ],
            options={
                'verbose_name': 'Listing image',
                'verbose_name_plural': 'Listing images',
                'ordering': ('-is_primary', 'position', 'id'),
            },
        ),
    ]
