# Generated by Django 6.0.6 on 2026-07-15 02:08

import django.db.models.deletion
from django.db import migrations, models


def fill_primary_listing(apps, schema_editor):
    ListingImage = apps.get_model("listings", "ListingImage")

    for listing_image in ListingImage.objects.filter(is_primary=True):
        listing_image.primary_listing_id = listing_image.listing_id
        listing_image.save(update_fields=("primary_listing",))


def clear_primary_listing(apps, schema_editor):
    ListingImage = apps.get_model("listings", "ListingImage")
    ListingImage.objects.update(primary_listing=None)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='primary_listing',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='listings.listing'),
        ),
        migrations.RunPython(fill_primary_listing, clear_primary_listing),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(fields=('primary_listing',), name='unique_primary_image_per_listing'),
        ),
    ]
