# Generated by Django 6.0.6 on 2026-07-18 17:31

import apps.listings.models.listing_image
import apps.listings.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingimage_primary_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(db_index=True, help_text='City where the listing is located.', max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='Detailed public description of the rental property.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='District or neighborhood where the listing is located.', max_length=100, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_number',
            field=models.CharField(help_text='House or building number of the rental property.', max_length=20, verbose_name='house number'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Controls whether the listing is visible in the public catalog.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(help_text='Landlord who owns this listing.', on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(help_text='Five-digit postal code.', max_length=5, validators=[django.core.validators.RegexValidator(message='Postal code must contain exactly 5 digits.', regex='^\\d{5}$')], verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Current price for one night.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room')], db_index=True, help_text='Type of rental property.', max_length=20, verbose_name='property type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Number of rooms in the rental property.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='rooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street',
            field=models.CharField(help_text='Street name of the rental property.', max_length=150, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Short public title of the rental property.', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(help_text='Uploaded image file for the listing.', upload_to=apps.listings.models.listing_image.listing_image_upload_path, validators=[apps.listings.validators.validate_listing_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marks this image as the main listing photo.', verbose_name='primary image'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(help_text='Listing this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order among listing images.', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='primary_listing',
            field=models.ForeignKey(blank=True, editable=False, help_text='Internal helper field used to enforce one primary image.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the image was uploaded.', verbose_name='uploaded at'),
        ),
    ]
