# Generated by Django 6.0.6 on 2026-07-18 17:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('listings', '0004_alter_listing_city_alter_listing_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(db_index=True, help_text='Checkout date; must be after the start date.', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(help_text='Listing reserved by this booking.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Snapshot of the listing price when the booking was created.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='renter',
            field=models.ForeignKey(help_text='User who created the booking.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(db_index=True, help_text='First day of the stay.', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Current booking workflow status.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total booking price calculated from dates and nightly price.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at'),
        ),
    ]
