# Generated by Django 6.0.6 on 2026-07-18 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_created_at_alter_booking_end_date_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(help_text='Completed booking this review belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional text comment from the renter.', max_length=2000, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at'),
        ),
    ]
